import UserDashNav from '@/components/Shared/UserDashNav/UserDashNav'
import '../globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en" data-theme="light">
      <body>
        <div className="">
          
          <UserDashNav childrens={children} />
        </div>
      </body>
    </html>
  )
}

