import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/Components/Shared/NavBar/NavBar'
import Footer from '@/Components/Shared/Footer/Footer'
import Head from 'next/head'
const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} 

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
     
       <body className={inter.className}>
        
        <div className=" max-w-[1366px] mx-auto">
          <NavBar  >{children} </NavBar>
          <Footer />

          {/* <div className="bg-[#FFF5E4]">
            {children}
          </div> */}
        </div>


      </body>
      
    </html>
  )
}
