import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/Shared/NavBar/NavBar'
import Footer from '@/components/Shared/Footer/Footer'
import WhyChoseUs from '@/Components/Home/WhyChooseUs/WhyChoseUs'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body className={inter.className}>
        <div className=" max-w-[1366px] mx-auto">
          <NavBar />

          <div className="bg-[#FFF5E4]">
            {children}
            
            <WhyChoseUs></WhyChoseUs>
          </div>
          <Footer />
        </div>


      </body>
    </html>
  )
}
